### ISSUE TITLE
XMLTemplate not working

### ISSUE THREAD

**Issue by drtebi** [jackrosenthal/kajiki#72]
I have tried the most simple example... as described in the docs, and it's just not working:
```
>>> import kajiki
>>> Template = kajiki.XMLTemplate('index.html', mode='html5')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/kajiki/xml_template.py", line 52, in XMLTemplate
    doc = _Parser(filename, source).parse()
  File "/usr/local/lib/python3.8/site-packages/kajiki/xml_template.py", line 695, in parse
    raise exc
kajiki.xml_template.XMLTemplateParseError: [<string>:1] syntax error
	 --> <!DOCTYPE kajiki SYSTEM "kajiki.dtd">index.html
```

My HTML file:
```
<!DOCTYPE html>
<html>
    <head><!--  Some stuff here  --></head>
    <body>
        <form>
            <input checked type="checkbox">
            <select>
                <option selected>One</option>
                <option>Two</option>
                <option>Three</option>
            </select>
        </form>
    </body>
</html>
```

This is on FreeBSD, Python 3.8, latest kajiki installed via pip.
I'd love to try this template engine... any ideas what's wrong?

**Comment by CastixGitHub** [comment]
Hello, first of all, you need to actually read the template file, eg: `open('index.html', 'r').read()`
Then the template itself is not valid, it isn't xhtml. in order to fix it, you need to:
1. change the attributes to `checked="checked"` and `selected="selected"`
2. close the input element `<input checked="checked" type="checkbox"/>`

I also suggesting you to use `.xhtml` or `.kajiki` for filenames.

Kajiki has the concept of TemplateLoader, as explained [in the docs](https://docs.kajiki.io/templating-basics.html?highlight=loader#python-api)

**Comment by drtebi** [comment]
Thank you for your response.

Regarding the well-formed template, I accidentally copied the output instead of the input from the documentation... 

The real culprit however was, that I didn't know I had to open and read the template first. While using `open` is one way, I see in the docstring that there is also a `filename` keyword argument. That seems simpler:
```
import kajiki
Template = kajiki.XMLTemplate(filename='index.html', mode='html5')
```

I wish the documentation was a bit more clear... I am a bit spoiled by the Qt documentation :)

**Comment by jackrosenthal** [comment]
If you find documentation improvements, please send them as a PR =)
