### ISSUE TITLE
Unit tests are failing on Python 3.11

### ISSUE THREAD

**Issue by jackrosenthal** [jackrosenthal/kajiki#75]
https://github.com/jackrosenthal/kajiki/runs/6941499171?check_suite_focus=true

**Comment by CastixGitHub** [comment]
Hi @jackrosenthal please see https://github.com/jackrosenthal/kajiki/pull/74/commits/61441162f0c381772a9216b0ea67c8293e9362ea

kajiki actually seems to work, but pytest is still failing due to some traceback manipulation? I don't think this is known by pytest devs, and I can't provide a minimal reproducible example...
